name: build and test
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm ci
      - run: nx lint
      - run: nx test
      - run: nx build
